### ISSUE TITLE
Error on direct use of acai-cli

### ISSUE THREAD

**Issue by LKuechler** [MartinHelmut/berries#11]
When using `npx @berries/acai-cli` it can not finish preinstall.
Node: 8.9.1

```
{ Error: Command failed: /Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/openssl/openssl
/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

 at ChildProcess.exithandler (child_process.js:275:12)
 at emitTwo (events.js:126:13)
 at ChildProcess.emit (events.js:214:7)
 at maybeClose (internal/child_process.js:925:16)
 at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/openssl/openssl' }
/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/openssl/openssl
/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

 at ChildProcess.exithandler (child_process.js:275:12)
 at emitTwo (events.js:126:13)
 at ChildProcess.emit (events.js:214:7)
 at maybeClose (internal/child_process.js:925:16)
 at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/laskue/.npm/_npx/64703/lib/node_modules/@berries/acai-cli/node_modules/nodegit/vendor/openssl/openssl' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.20.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.20.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/laskue/.npm/_logs/2018-01-21T14_01_06_964Z-debug.log
Install for @berries/acai-cli@latest failed with code 1
```

**Comment by LKuechler** [comment]
If i can support you with anything on this issue, let me know :)

**Comment by LKuechler** [comment]
Also happens when trying to install it globally: `npm i @berries/acai-cli -g`

**Comment by LKuechler** [comment]
seems to be a problem with a update from osx and should happen with every package...
https://github.com/nodegit/nodegit/issues/1134

**Comment by MartinHelmut** [comment]
Thanks for reporting! 👍 Was after following the steps mentioned in that nodegit issue everything okay?

**Comment by LKuechler** [comment]
Yes, that fixed it.
Works great on the Alva project

**Comment by MartinHelmut** [comment]
Nice! 😊
